[build]
builder = "nixpacks"

[deploy]
startCommand = "chmod +x scripts/start.sh && ./scripts/start.sh"
restartPolicyType = "on_failure"

[environments.production.variables]
NODE_ENV = "production"
DATABASE_URL = "file:./prod.db"